"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# In local/dev runs, prefer values from .env over stale shell-exported variables.
load_dotenv(override=True)

QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
QDRANT_TIMEOUT_SEC = float(os.getenv("QDRANT_TIMEOUT_SEC", "30"))
QDRANT_COLLECTION_NAME = os.getenv("QDRANT_COLLECTION_NAME", "documents")
# Vector size must match the active embedding model output dimension.
QDRANT_VECTOR_SIZE = int(os.getenv("QDRANT_VECTOR_SIZE", "4096"))
# If the Qdrant collection uses named vectors (e.g. created in Cloud UI), set this to that name.
QDRANT_VECTOR_NAME = os.getenv("QDRANT_VECTOR_NAME", "").strip() or None
# Optional safety valve: if true, drop and recreate the collection when vector size mismatches.
# WARNING: this deletes all vectors in that collection.
QDRANT_AUTO_RECREATE_ON_DIMENSION_MISMATCH = os.getenv(
    "QDRANT_AUTO_RECREATE_ON_DIMENSION_MISMATCH", "0"
).strip().lower() in {"1", "true", "yes", "y", "on"}
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
OPENROUTER_REFERER = os.getenv("OPENROUTER_REFERER", "http://localhost:8000")
OPENROUTER_TITLE = os.getenv("OPENROUTER_TITLE", "chatbot-backend")

# OpenRouter model defaults (override via env vars when deploying).
OPENROUTER_CHAT_MODEL = os.getenv("OPENROUTER_CHAT_MODEL", "qwen/qwen3.6-plus:free")
OPENROUTER_EMBEDDING_MODEL = os.getenv("OPENROUTER_EMBEDDING_MODEL", "qwen/qwen3-embedding-8b")
OPENROUTER_MAX_OUTPUT_TOKENS = int(os.getenv("OPENROUTER_MAX_OUTPUT_TOKENS", "1024"))
OPENROUTER_TEMPERATURE = float(os.getenv("OPENROUTER_TEMPERATURE", "0.1"))
# Seconds for each OpenRouter HTTP call (prevents indefinite hangs; raise if answers truncate often).
OPENROUTER_HTTP_TIMEOUT_SEC = float(os.getenv("OPENROUTER_HTTP_TIMEOUT_SEC", "120"))
# Embeddings can hit upstream 408s; allow a longer client read timeout than chat.
OPENROUTER_EMBEDDING_TIMEOUT_SEC = float(os.getenv("OPENROUTER_EMBEDDING_TIMEOUT_SEC", "180"))
OPENROUTER_EMBEDDING_MAX_RETRIES = int(os.getenv("OPENROUTER_EMBEDDING_MAX_RETRIES", "6"))
OPENROUTER_MAX_CONTINUATIONS = int(os.getenv("OPENROUTER_MAX_CONTINUATIONS", "1"))
# Optional second pass: shorten the chat model's answer (same or separate model).
OPENROUTER_SUMMARY_MODEL = os.getenv("OPENROUTER_SUMMARY_MODEL", "").strip() or None
OPENROUTER_SUMMARY_MAX_OUTPUT_TOKENS = int(os.getenv("OPENROUTER_SUMMARY_MAX_OUTPUT_TOKENS", "384"))
RAG_LLM_POST_SUMMARY = os.getenv("RAG_LLM_POST_SUMMARY", "0").strip().lower() in {
    "1",
    "true",
    "yes",
    "y",
    "on",
}
# Only run the summary pass when the beautified answer is at least this long (characters).
RAG_SUMMARIZE_MIN_INPUT_CHARS = int(os.getenv("RAG_SUMMARIZE_MIN_INPUT_CHARS", "200"))

# RAG defaults
RAG_TOP_K = int(os.getenv("RAG_TOP_K", "6"))
# Dense cosine-style similarity floor (lower = more recall).
RAG_SIMILARITY_THRESHOLD = float(os.getenv("RAG_SIMILARITY_THRESHOLD", "0.15"))
# Keep chunks scoring at least this fraction of the best dense hit (improves recall).
RAG_SEMANTIC_RELATIVE_FLOOR = float(os.getenv("RAG_SEMANTIC_RELATIVE_FLOOR", "0.78"))
# Set true only if your Qdrant scores are distances (lower = better), not similarities.
RAG_SEMANTIC_SCORE_LOWER_IS_BETTER = os.getenv("RAG_SEMANTIC_SCORE_LOWER_IS_BETTER", "").strip().lower() in {
    "1",
    "true",
    "yes",
    "y",
    "on",
}
RAG_MAX_CONTEXT_TOKENS = int(os.getenv("RAG_MAX_CONTEXT_TOKENS", "2800"))
# When packing context, skip a tiny tail smaller than this (tokens) unless it is the first chunk.
RAG_CONTEXT_MIN_TAIL_TOKENS = int(os.getenv("RAG_CONTEXT_MIN_TAIL_TOKENS", "100"))
# Dense search pool size = max(top_k * multiplier, min_below).
RAG_SEMANTIC_CANDIDATE_MULTIPLIER = int(os.getenv("RAG_SEMANTIC_CANDIDATE_MULTIPLIER", "16"))
RAG_SEMANTIC_CANDIDATE_MIN = int(os.getenv("RAG_SEMANTIC_CANDIDATE_MIN", "96"))
RAG_INGEST_CHUNK_SIZE_TOKENS = int(os.getenv("RAG_INGEST_CHUNK_SIZE_TOKENS", "420"))
RAG_INGEST_CHUNK_OVERLAP_TOKENS = int(os.getenv("RAG_INGEST_CHUNK_OVERLAP_TOKENS", "80"))
# Lexical channel: scroll page size and max total points (large values slow each request).
RAG_LEXICAL_SCAN_LIMIT = int(os.getenv("RAG_LEXICAL_SCAN_LIMIT", "150"))
RAG_LEXICAL_MAX_POINTS = int(os.getenv("RAG_LEXICAL_MAX_POINTS", "1200"))
# Always merge at least this many top RRF rows into context (deduped by chunk).
RAG_RRF_MIN_GUARANTEE = int(os.getenv("RAG_RRF_MIN_GUARANTEE", "3"))
# Additional RRF union slots relative to top_k (kept small to reduce weak tails).
RAG_RRF_UNION_MULTIPLIER = int(os.getenv("RAG_RRF_UNION_MULTIPLIER", "4"))
# Reciprocal rank fusion k (standard ~60). Merges dense + BM25 lists every query.
RAG_HYBRID_RRF_K = int(os.getenv("RAG_HYBRID_RRF_K", "60"))
# Min BM25 score for a lexical-only hit to pass the filter.
RAG_LEXICAL_BM25_MIN = float(os.getenv("RAG_LEXICAL_BM25_MIN", "0.35"))
# If true, block some queries as "gibberish" BEFORE embeddings/Qdrant (can false-positive real HR questions).
RAG_ENABLE_GIBBERISH_FILTER = os.getenv("RAG_ENABLE_GIBBERISH_FILTER", "0").strip().lower() in {
    "1",
    "true",
    "yes",
    "y",
    "on",
}

# Strict, non-hallucinating answering mode:
# - When enabled, responses are assembled from verbatim sentences found in retrieved chunks.
# - When disabled, the LLM can paraphrase (higher fluency, lower guarantee).
RAG_STRICT_NO_HALLUCINATE = os.getenv("RAG_STRICT_NO_HALLUCINATE", "1").strip().lower() in {"1", "true", "yes", "y", "on"}
# Sentences selected for strict extractive answers (embedding-ranked).
RAG_STRICT_MAX_SENTENCES = int(os.getenv("RAG_STRICT_MAX_SENTENCES", "5"))
# How many cleaned sentences to join into the main paragraph (can be > selection count).
RAG_STRICT_ANSWER_BODY_SENTENCES = int(os.getenv("RAG_STRICT_ANSWER_BODY_SENTENCES", "8"))
RAG_STRICT_MAX_CONTEXT_TOKENS = int(os.getenv("RAG_STRICT_MAX_CONTEXT_TOKENS", "1800"))
RAG_STRICT_ANSWER_BODY_CHARS = int(os.getenv("RAG_STRICT_ANSWER_BODY_CHARS", "2800"))
RAG_STRICT_MAX_CHUNKS_FOR_BODY = int(os.getenv("RAG_STRICT_MAX_CHUNKS_FOR_BODY", "3"))
# Drop strict-mode chunks whose context BM25 is below this fraction of the best chunk (0 = off).
RAG_STRICT_BM25_RELATIVE_FLOOR = float(os.getenv("RAG_STRICT_BM25_RELATIVE_FLOOR", "0.12"))
# Prefer lines that match query terms (fewer unrelated policy paragraphs in the answer).
RAG_STRICT_QUERY_FOCUSED_BODY = os.getenv("RAG_STRICT_QUERY_FOCUSED_BODY", "1").strip().lower() in {
    "1",
    "true",
    "yes",
    "y",
    "on",
}
# If strict verbatim assembly returns nothing, call the LLM (can invent; default off).
RAG_STRICT_FALLBACK_TO_LLM = os.getenv("RAG_STRICT_FALLBACK_TO_LLM", "0").strip().lower() in {
    "1",
    "true",
    "yes",
    "y",
    "on",
}
# If false, strict mode does not widen into broad non-focused paragraph assembly.
RAG_STRICT_ALLOW_BROAD_BODY_FALLBACK = os.getenv(
    "RAG_STRICT_ALLOW_BROAD_BODY_FALLBACK", "1"
).strip().lower() in {"1", "true", "yes", "y", "on"}
# Query-focused extraction includes +/- this many lines around each anchor hit.
RAG_STRICT_ANCHOR_WINDOW_LINES = int(os.getenv("RAG_STRICT_ANCHOR_WINDOW_LINES", "1"))
# Minimum query-term overlap required for strict sentence extraction.
RAG_STRICT_MIN_SENTENCE_OVERLAP = int(os.getenv("RAG_STRICT_MIN_SENTENCE_OVERLAP", "2"))
# Max bullet lines in strict sentence fallback.
RAG_STRICT_EXTRACTIVE_MAX_BULLETS = int(os.getenv("RAG_STRICT_EXTRACTIVE_MAX_BULLETS", "10"))
# Calibrated abstention gate: minimum score required to answer from retrieved context.
RAG_MIN_ANSWERABILITY_SCORE = float(os.getenv("RAG_MIN_ANSWERABILITY_SCORE", "0.42"))

# Embeddings batching (provider-dependent)
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "64"))

# Top-tier retrieval/ranking toggles (all safe defaults).
RAG_ENABLE_CROSS_ENCODER_RERANK = os.getenv("RAG_ENABLE_CROSS_ENCODER_RERANK", "0").strip().lower() in {
    "1", "true", "yes", "y", "on"
}
RAG_CROSS_ENCODER_MODEL = os.getenv("RAG_CROSS_ENCODER_MODEL", "cross-encoder/ms-marco-MiniLM-L-6-v2")
RAG_CROSS_ENCODER_TOP_N = int(os.getenv("RAG_CROSS_ENCODER_TOP_N", "30"))
RAG_ENABLE_LEXICAL_INDEX_CACHE = os.getenv("RAG_ENABLE_LEXICAL_INDEX_CACHE", "1").strip().lower() in {
    "1", "true", "yes", "y", "on"
}
RAG_ENABLE_SPARSE_LEXICAL_INDEX = os.getenv("RAG_ENABLE_SPARSE_LEXICAL_INDEX", "1").strip().lower() in {
    "1", "true", "yes", "y", "on"
}
RAG_LEXICAL_INDEX_TTL_SEC = int(os.getenv("RAG_LEXICAL_INDEX_TTL_SEC", "300"))
RAG_AB_TEST_ENABLED = os.getenv("RAG_AB_TEST_ENABLED", "0").strip().lower() in {
    "1", "true", "yes", "y", "on"
}
RAG_TELEMETRY_ENABLED = os.getenv("RAG_TELEMETRY_ENABLED", "1").strip().lower() in {
    "1", "true", "yes", "y", "on"
}
RAG_SENTENCE_EVIDENCE_MIN_OVERLAP = int(os.getenv("RAG_SENTENCE_EVIDENCE_MIN_OVERLAP", "2"))
RAG_REGRESSION_ALERT_MIN_SAMPLES = int(os.getenv("RAG_REGRESSION_ALERT_MIN_SAMPLES", "50"))

# Fix Django unittest runner incompatibility in this environment.
TEST_RUNNER = "chatbot.test_runner.NoDurationsDiscoverRunner"

# Basic rate limiting to protect embeddings/LLM endpoints.
# Uses IP-based throttling for anonymous requests by default.
REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "60/min",
        "anon": "30/min",
    },
    # Keep auth as-is for now; throttle works fine without authentication.
    "DEFAULT_AUTHENTICATION_CLASSES": [],
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j9ig_1zi89392dgg8+vdvq11-2&ax3^z-j__3q7^zz!%8y+9nm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.50.137"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'corsheaders',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    ]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]


CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
     'default' :{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'chatbot_database',
        'PASSWORD': 'acme',
        'USER': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432'
     }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
