# Generated by Django 6.0.3 on 2026-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('query', models.TextField()),
                ('retrieved_chunk_ids', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(max_length=128)),
                ('response_text', models.TextField()),
                ('latency_ms', models.IntegerField()),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='total_chunks',
        ),
        migrations.RemoveField(
            model_name='document',
            name='total_tokens',
        ),
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='content_length',
            field=models.IntegerField(blank=True, help_text='Total length of normalized text (characters).', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_count',
            field=models.IntegerField(blank=True, help_text='Total number of vectors stored in Qdrant.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='ready', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='token_count',
            field=models.IntegerField(blank=True, help_text='Total number of (approx) tokens embedded across all chunks.', null=True),
        ),
    ]
